apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/pachr/argocd-demo.git
      revision: HEAD
      files:
      - path: "argocd-projects/*-project.yaml"
  template:
    metadata:
      name: 'bootstrap-team1'
    spec:
      project: default
      source:
        repoURL: https://github.com/pachr/argocd-demo.git
        targetRevision: master
        path: argocd-projects/argocd-project-chart
        helm:
          releaseName: test
          valueFiles:
          - ../home-project.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
