apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-apps
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/pachr/argocd-demo.git
          revision: HEAD
          directories:
          - path: helm-charts/home/*
      - list:
          elements:
          - environment: dev
          - environment: staging
          - environment: prod
  template:
    metadata:
      name: 'home-{{path.basename}}-{{environment}}'
    spec:
      project: home-project
      source:
        repoURL: https://github.com/pachr/argocd-demo.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - '../../env-values/{{environment}}.yaml'
      destination:
        server: '{{values.clusterUrl}}'
        namespace: 'home-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
