apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/pachr/argocd-demo.git
      revision: HEAD
      files:
      - path: "argocd-projects/*-project.yaml"
  template:
    metadata:
      name: 'bootstrap-{{.projectName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/pachr/argocd-demo.git
        targetRevision: HEAD
        path: argocd-projects
        helm:
          releaseName: '{{.projectName}}'
          valueFiles:
          - '{{.path.filename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
